openapi: 3.0.3
info:
  title: Menumemory Backend
  version: 0.1.0
servers:
  - url: http://localhost:8080
tags:
  - name: health
    description: Metadata about the server health
  - name: restaurant
    description: Everything about restaurants
paths:
  /ping:
    get:
      tags:
        - health
      summary: Check if API is alive
      description: Returns a Pong message to indicate that the backend API is live and running
      responses:
        '200':
          description: Server is alive
  /restaurants:
    get:
      tags:
        - restaurant
      summary: Get restaurants matching a search term
      description: Get restaurants matching a search term
      parameters:
        - name: search_term
          in: query
          description: The search term aginst which matching restaurants are returned
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: string
        '400':
          description: "search_term was not sent"

