// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Dish struct {
	ID   int64
	Name string
}

type Order struct {
	ID         int64
	Visitid    sql.NullInt64
	Dishid     sql.NullInt64
	Rating     sql.NullFloat64
	Reviewtext sql.NullString
}

type Restaurant struct {
	ID               int64
	Name             string
	Area             sql.NullString
	Address          sql.NullString
	Mapslink         sql.NullString
	Mapsratingoutof5 sql.NullFloat64
}

type User struct {
	ID        int64
	Email     string
	Firstname sql.NullString
	Lastname  sql.NullString
	Dob       sql.NullTime
}

type Visit struct {
	ID           int64
	Date         time.Time
	Time         interface{}
	Userid       sql.NullInt64
	Restaurantid sql.NullInt64
}
